#!/usr/bin/bash

OUTDIR=./output
echo "Attempting to create directory $OUTDIR"
mkdir -p $OUTDIR
echo

echo "Running Euler method..."
./bin/myEuler
echo

echo "Running Euler Predictor-Corrector method..."
./bin/myEulerPC
echo

echo "Running ODEINT method..."
./bin/myODEINT
echo

FIGDIR=./output/figs
echo "Attempting to create directory $FIGDIR"
mkdir -p $FIGDIR
python3 ./plot.py
echo

echo "Complete."
